<?php 
    return [
        'shipping_hubfulfill' => [
            'Bulgaria' => 'EUYTECO',
            'Latvia' => 'EUYTECO',
            'Norway' => 'EUYTECO',
            'Malta' => 'EUYTECO',
            'Greece' => 'EUYTECO',
            'Netherlands' => 'EUYTECO',
            'Lithuania' => 'EUYTECO',
            'Denmark' => 'EUYTECO',
            'Caribbean Netherlands' => 'EUYTECO',
            'Finland' => 'EUYTECO',
            'France' => 'EUYTECO',
            'Cyprus' => 'EUYTECO',
            'Austria' => 'EUYTECO',
            'Croatia' => 'EUYTECO',
            'Slovakia' => 'EUYTECO',
            'Estonia' => 'EUYTECO',
            'Italy' => 'EUYTECO',
            'United Kingdom' => 'EUYTECO',
            'Czechia' => 'EUYTECO',
            'Ireland' => 'EUYTECO',
            'Portugal' => 'EUYTECO',
            'Poland' => 'EUYTECO',
            'Germany' => 'EUYTECO',
            'Israel' => 'EUYTECO',
            'Slovenia' => 'EUYTECO',
            'Sweden' => 'EUYTECO',
            'Hungary' => 'EUYTECO',
            'Spain' => 'EUYTECO',
            'Singapore' => 'EUYTECO',
            'Belgium' => 'EUYTECO',
            'Romania' => 'EUYTECO',
            'Luxembourg' => 'EUYTECO',
            'United States' => 'USUSPSEX',
            'Vietnam' => 'VNVNP',      
            'Switzerland' => 'CHYTECO',
            'Mexico' => 'MXYTECO',
            'New Zealand' => 'NZYTECO',
            'Australia' => 'AUYTECO',
            'Canada' => 'CAYTECO',
        ]   
        
    ];
?>