<?php 
    return [
        'shipping_hubfulfill' => [
            'Bulgaria' => 'EUYTECO',
            'Latvia' => 'EUYTECO',
            'Norway' => 'EUYTECO',
            'Malta' => 'EUYTECO',
            'Greece' => 'EUYTECO',
            'Netherlands' => 'EUYTECO',
            'Lithuania' => 'EUYTECO',
            'Denmark' => 'EUYTECO',
            'Caribbean Netherlands' => 'EUYTECO',
            'Finland' => 'EUYTECO',
            'France' => 'EUYTECO',
            'Cyprus' => 'EUYTECO',
            'Austria' => 'EUYTECO',
            'Croatia' => 'EUYTECO',
            'Slovakia' => 'EUYTECO',
            'Estonia' => 'EUYTECO',
            'Italy' => 'EUYTECO',
            'United Kingdom' => 'EUYTECO',
            'Czechia' => 'EUYTECO',
            'Ireland' => 'EUYTECO',
            'Portugal' => 'EUYTECO',
            'Poland' => 'EUYTECO',
            'Germany' => 'EUYTECO',
            'Israel' => 'EUYTECO',
            'Slovenia' => 'EUYTECO',
            'Sweden' => 'EUYTECO',
            'Hungary' => 'EUYTECO',
            'Spain' => 'EUYTECO',
            'Singapore' => 'EUYTECO',
            'Belgium' => 'EUYTECO',
            'Romania' => 'EUYTECO',
            'Luxembourg' => 'EUYTECO',
            'United States' => 'USUSPSEX',
          
            'Vietnam' => 'VNVNP',      
            'Switzerland' => 'CHYTECO',
            'Mexico' => 'MXYTECO',
            'New Zealand' => 'NZYTECO',
            'Australia' => 'AUYTECO',
            'Canada' => 'CAYTECO',
        ] ,
        
        'felix_size_otb' => [
            'ADULT_SWEATSHIRT_2D' => 'SS-',
            'ADULT_UNISEX_HOODIE' => 'H-',
            'BELLA_CANVAS_TSHIRT' => 'BC-',
            'COMFORT_COLORS_LONG_SLEEVE' => 'CFLS-',
            'COMFORT_COLORS_SHIRT' => 'CF-',
            'STANDARD_LONG_SLEEVE' => 'LS-',
            'WOMEN_TSHIRT' => 'W-',
            'Y_PULLOVER_HOODIE' => 'YH-',
            'Y_TSHIRT' => 'Y-',
        ],

        'sizeShirt' => [
            'NB (0-3M)',
            '12M',
            '18M',
            '24M',
            '2T',
            '3T',
            '4T',
            '5T',
            '5T-6T',
            'L',
            'M',
            'S',
            'XL',
            '2XL',
            '3XL',
            '4XL',
            '5XL',
            '6M',
            '8Y',
            '10Y'
        ],

        'sizeStyle' => [
            '14x14',
            '16x16',
            '18x18',
            '20x20',
        ],

        'sizeCanvas' => [
            "9'' x 11''",
            "8'' x 10''",
            "10'' x 10''",
            "10'' x 20''",
            "11'' x 14''",
            "12'' x 12''",
            "12'' x 16''",
            "12'' x 18''",
            "12'' x 36''",
            "15'' x 30''",
            "16'' x 16''",
            "16'' x 20''",
            "16'' x 24''",
            "18'' x 24''",
            "20'' x 20''",
            "20'' x 24''",
            "20'' x 30''",
            "20'' x 40''",
            "20'' x 60''",
            "24'' x 24''",
            "24'' x 30''",
            "24'' x 36''",
            "24'' x 48''",
            "30'' x 30''",
            "30'' x 40''",
            "30'' x 60''",
            "32'' x 48''",
            "36'' x 36''",
            "36'' x 48''"
        ],

        'productTasks' => [
            "T-shirt",
            "Flag",
            "Blanket",
            "Doormat",
            "Fabric",
            "Metal Sign",
            "License Plate",
            "Metal Licence Plate Frame",
            "Poster"
        ],

        'platformSizeTasks' => [
            "Printify",
            "OTB",
            "S",
            "L",
            "Wall Flag/ 3x5 feet/ 4x6 feet",
            "Fleece 30x40 inch",
            "Fleece 50x60 inch",
            "Fleece 60x80 inch",
            "Fleece (Printify) 30x40 inch",
            "Fleece (Printify) 50x60 inch",
            "Fleece (Printify) 60x80 inch",
            "Fleece (interestPrint) 50x60 inch",
            "Premium Fleece FLEB",
            "Premium Fleece FLEB2CW",
            "Minky (Printify) 30x40 inch",
            "Minky (Printify) 50x60 inch",
            "Minky (Printify) 60x80 inch",
            "Minky 30x40 inch",
            "Minky 50x60 inch",
            "Sherpa (Printify) 50x60 inch",
            "Sherpa (Printify) 60x80 inch",
            "Sherpa PicTheGift 30x40 inch",
            "Sherpa PicTheGift 50x60 inch",
            "Sherpa PicTheGift 60x80 inch",
            "Woven Lenful",
            "Woven 50x60 inch",
            "Woven 60x80 inch",
            "Wall Tapestry 34x40 inch",
            "Wall Tapestry 50x60 inch",
            "Wall Tapestry 80x68 inch",
            "Rubber 24x16 inch",
            "Rubber 30x18 inch, 200 DPI",
            "Rubber 24x18 inch, 200 DPI",
            "Fabric size 18x30, 24x35, 20x35, 15x25, 150 DPI",
            "Fabric size 18x24",
            "Fabric size 35x42",
            "8 inch",
            "12 inch",
            "14 inch",
            "18 inch",
            "8x8 inch",
            "12x12 inch",
            "14x14 inch",
            "18x18 inch",
            "24x24 inch",
            "9x11 inch",
            "11x14 inch",
            "11x17 inch",
            "12x18 inch",
            "16x20 inch",
            "18x24 inch",
            "20x30 inch",
            "Custom Cat Poster"
        ] 
    ];
?>