<?php 
    return [
        'shipping_hubfulfill' => [
            'Bulgaria' => 'EUYTECO',
            'Latvia' => 'EUYTECO',
            'Norway' => 'EUYTECO',
            'Malta' => 'EUYTECO',
            'Greece' => 'EUYTECO',
            'Netherlands' => 'EUYTECO',
            'Lithuania' => 'EUYTECO',
            'Denmark' => 'EUYTECO',
            'Caribbean Netherlands' => 'EUYTECO',
            'Finland' => 'EUYTECO',
            'France' => 'EUYTECO',
            'Cyprus' => 'EUYTECO',
            'Austria' => 'EUYTECO',
            'Croatia' => 'EUYTECO',
            'Slovakia' => 'EUYTECO',
            'Estonia' => 'EUYTECO',
            'Italy' => 'EUYTECO',
            'United Kingdom' => 'EUYTECO',
            'Czechia' => 'EUYTECO',
            'Ireland' => 'EUYTECO',
            'Portugal' => 'EUYTECO',
            'Poland' => 'EUYTECO',
            'Germany' => 'EUYTECO',
            'Israel' => 'EUYTECO',
            'Slovenia' => 'EUYTECO',
            'Sweden' => 'EUYTECO',
            'Hungary' => 'EUYTECO',
            'Spain' => 'EUYTECO',
            'Singapore' => 'EUYTECO',
            'Belgium' => 'EUYTECO',
            'Romania' => 'EUYTECO',
            'Luxembourg' => 'EUYTECO',
            'United States' => 'USUSPSEX',
          
            'Vietnam' => 'VNVNP',      
            'Switzerland' => 'CHYTECO',
            'Mexico' => 'MXYTECO',
            'New Zealand' => 'NZYTECO',
            'Australia' => 'AUYTECO',
            'Canada' => 'CAYTECO',
        ] ,
        
        'felix_size_otb' => [
            'ADULT_SWEATSHIRT_2D' => 'SS-',
            'ADULT_UNISEX_HOODIE' => 'H-',
            'BELLA_CANVAS_TSHIRT' => 'BC-',
            'COMFORT_COLORS_LONG_SLEEVE' => 'CFLS-',
            'COMFORT_COLORS_SHIRT' => 'CF-',
            'STANDARD_LONG_SLEEVE' => 'LS-',
            'WOMEN_TSHIRT' => 'W-',
            'Y_PULLOVER_HOODIE' => 'YH-',
            'Y_TSHIRT' => 'Y-',
        ],

        'sizeShirt' => [
            'NB (0-3M)',
            '6M',
            '12M',
            '18M',
            '24M',
            '2T',
            '3T',
            '4T',
            '5T',
            '5T-6T',
            'L',
            'M',
            'S',
            'XL',
            '2XL',
            '3XL',
            '4XL',
            '5XL',
        ],

        'sizeStyle' => [
            '14x14',
            '16x16',
            '18x18',
            '20x20',
        ],

        'sizeCanvas' => [
            '9" x 11"',
            '8" x 10"',
            '10" x 10"',
            '10" x 20"',
            '11" x 14"',
            '12" x 12"',
            '12" x 16"',
            '12" x 18"',
            '12" x 36"',
            '15" x 30"',
            '16" x 16"',
            '16" x 20"',
            '16" x 24"',
            '18" x 24"',
            '20" x 20"',
            '20" x 24"',
            '20" x 30"',
            '20" x 40"',
            '20" x 60"',
            '24" x 24"',
            '24" x 30"',
            '24" x 36"',
            '24" x 48"',
            '30" x 30"',
            '30" x 40"',
            '30" x 60"',
            '32" x 48"',
            '36" x 36"',
            '36" x 48"'
        ],
    ];
?>